#!/usr/bin/env bun
/**
 * BUNZ Bundler - Critical Path Optimizer
 * Bundles core framework files into main.js
 * Reduces critical path from 4 HTTP requests to 1
 */

import { readFile, writeFile } from 'fs/promises';

async function bundle() {
    console.log('\n╔══════════════════════════════════════════════════════════╗');
    console.log('║                                                          ║');
    console.log('║              📦 BUNZ Framework Bundler 📦               ║');
    console.log('║                                                          ║');
    console.log('╚══════════════════════════════════════════════════════════╝\n');
    
    try {
        console.log('📋 Bundling critical path scripts...\n');
        
        // Core files that must load first (in order)
        const coreFiles = [
            { path: 'src/client/js/core/loader.js', name: 'Loader' },
            { path: 'src/client/js/core/lifecycle.js', name: 'Lifecycle' },
            { path: 'src/client/js/core/scripts.js', name: 'Scripts' },
            { path: 'src/client/js/core/core.js', name: 'Core' },
            { path: 'src/client/js/core/routing.js', name: 'Routing' }
        ];
        
        // Output path
        const mainPath = 'src/client/main.js';
        
        // Build bundle
        const bundleParts = [
            '/**',
            ' * BUNZ Framework - Bundled Critical Path',
            ' * Auto-generated by tools/bundle.ts',
            ' * Contains: loader.js + lifecycle.js + scripts.js + core.js + routing.js',
            ' * DO NOT EDIT - Run `bun run bundle` to regenerate',
            ' */',
            ''
        ];
        
        // Add each core file
        for (const file of coreFiles) {
            const content = await readFile(file.path, 'utf-8');
            const size = content.length;
            
            bundleParts.push(
                `// ============================================================================`,
                `// ${file.name.toUpperCase()} (${(size / 1024).toFixed(1)} KB)`,
                `// Source: ${file.path}`,
                `// ============================================================================`,
                '',
                content.replace(/^'use strict';\s*/gm, ''), // Remove duplicate 'use strict'
                ''
            );
            
            console.log(`  ✅ Bundled ${file.name.padEnd(12)} ${size.toString().padStart(6)} bytes`);
        }
        
        // Add single 'use strict' at the top
        const bundled = `'use strict';\n\n${bundleParts.join('\n')}`;
        
        // Write bundled file
        await writeFile(mainPath, bundled, 'utf-8');
        
        const totalSize = bundled.length;
        
        console.log('╔══════════════════════════════════════════════════════════╗');
        console.log('║                                                          ║');
        console.log('║                  ✅ Bundling Complete! ✅               ║');
        console.log('║                                                          ║');
        console.log('╚══════════════════════════════════════════════════════════╝\n');
        
        console.log(`📂 Output: src/client/main.js`);
        console.log(`📦 Total size: ${(totalSize / 1024).toFixed(1)} KB`);
        console.log(`📈 Files bundled: ${coreFiles.length} → 1`);
        console.log(`⚡ HTTP requests saved: ${coreFiles.length - 1} fewer round trips!\n`);
        
        console.log('💡 Next steps:');
        console.log('1. Run `bun run minify` to generate minified version');
        console.log('2. Test with `bun run dev`\n');
        
    } catch (error) {
        console.error('\n❌ Bundling failed:', error);
        process.exit(1);
    }
}

bundle();

